# setting env to production will minify the html
#env: production
env: dev

exclude: ['Gruntfile.js', 'buildspec.yml', 'Gemfile', 'Gemfile.lock', 'package.json', 'package-lock.json', 'README.md', 'sftpCache.json' ,'node_modules']
    
sass:
  sass_dir: _scss
  style: compressed

title: Army Style Guide

