version: 0.2

phases:
  install:
    commands:
        - echo "******** CHANGE BRANCH ********"
        - git checkout $GIT_BRANCH
        - gem install bundler
        - gem list bundle
        - bundle install
        - npm install
  build:
    commands:
        - export LC_ALL=en_US.UTF-8
        - echo "******** Run Grunt Task ********"
        - grunt production
        - echo "******** Building Jekyll site ********"
        - bundle exec jekyll build
        - echo "******** Uploading to S3 ********"
        - aws s3 sync _site/ s3://$S3_BUCKET/globalstyles --exclude "e2/*"
        - aws s3 sync _site/e2/js/rv7/armydotmil s3://$S3_BUCKET/e2/js/rv7/armydotmil
        - aws s3 sync _site/e2/css/rv7/armydotmil s3://$S3_BUCKET/e2/css/rv7/armydotmil
        - aws s3 sync _site/e2/css/rv7/upgrade s3://$S3_BUCKET/e2/css/rv7/upgrade
        - aws s3 sync _site/e2/images/rv7/upgrade s3://$S3_BUCKET/e2/images/rv7/upgrade
